// AUTO-GENERATED by scripts/backfill-eipip.ts — do not edit by hand.
// Source: ethereum/pm + ethcatherders/EIPIP issues titled "EIPIP Meeting ...".
// Regenerate: GITHUB_ACCESS_TOKEN=... npx tsx scripts/backfill-eipip.ts

export type EipipMeeting = {
  meeting: number;
  dateISO: string;   // yyyy-mm-dd (from body, title, or issue creation date)
  timeUTC: string | null; // "HH:MM" in UTC, or null if unstated
  title: string;
  issueUrl: string;
  repo: string;
  cfiCount: number;       // Call-for-Input rows parsed from the agenda (recent meetings only)
  discussionCount: number; // editors' discussion items parsed from the agenda
};

export const EIPIP_MEETINGS: EipipMeeting[] = [
  {
    "meeting": 130,
    "dateISO": "2026-09-16",
    "timeUTC": "16:00",
    "title": "EIPIP Meeting #130, Sep 16, 2026",
    "issueUrl": "https://github.com/ethereum/pm/issues/2190",
    "repo": "ethereum/pm",
    "cfiCount": 2,
    "discussionCount": 1
  },
  {
    "meeting": 129,
    "dateISO": "2026-08-12",
    "timeUTC": "16:00",
    "title": "EIPIP Meeting #129, Aug 12, 2026",
    "issueUrl": "https://github.com/ethereum/pm/issues/2159",
    "repo": "ethereum/pm",
    "cfiCount": 2,
    "discussionCount": 3
  },
  {
    "meeting": 128,
    "dateISO": "2026-07-08",
    "timeUTC": "16:00",
    "title": "EIPIP Meeting #128, July 08, 2026",
    "issueUrl": "https://github.com/ethereum/pm/issues/2106",
    "repo": "ethereum/pm",
    "cfiCount": 3,
    "discussionCount": 3
  },
  {
    "meeting": 127,
    "dateISO": "2026-06-03",
    "timeUTC": "16:00",
    "title": "EIPIP Meeting #127, June 03, 2026",
    "issueUrl": "https://github.com/ethereum/pm/issues/2086",
    "repo": "ethereum/pm",
    "cfiCount": 3,
    "discussionCount": 2
  },
  {
    "meeting": 126,
    "dateISO": "2026-05-27",
    "timeUTC": "16:00",
    "title": "EIPIP Meeting #126, May 27, 2026",
    "issueUrl": "https://github.com/ethereum/pm/issues/2062",
    "repo": "ethereum/pm",
    "cfiCount": 5,
    "discussionCount": 3
  },
  {
    "meeting": 125,
    "dateISO": "2026-04-15",
    "timeUTC": "16:00",
    "title": "EIPIP Meeting #125, April 15, 2026",
    "issueUrl": "https://github.com/ethereum/pm/issues/1975",
    "repo": "ethereum/pm",
    "cfiCount": 5,
    "discussionCount": 4
  },
  {
    "meeting": 124,
    "dateISO": "2026-02-25",
    "timeUTC": "16:00",
    "title": "EIPIP Meeting #124, Feb 25, 2026",
    "issueUrl": "https://github.com/ethereum/pm/issues/1934",
    "repo": "ethereum/pm",
    "cfiCount": 0,
    "discussionCount": 0
  },
  {
    "meeting": 123,
    "dateISO": "2026-01-21",
    "timeUTC": "16:00",
    "title": "EIPIP Meeting #123, Jan 21, 2026",
    "issueUrl": "https://github.com/ethereum/pm/issues/1886",
    "repo": "ethereum/pm",
    "cfiCount": 0,
    "discussionCount": 2
  },
  {
    "meeting": 122,
    "dateISO": "2025-12-17",
    "timeUTC": "16:00",
    "title": "EIPIP Meeting #122, Dec 17, 2025",
    "issueUrl": "https://github.com/ethereum/pm/issues/1777",
    "repo": "ethereum/pm",
    "cfiCount": 0,
    "discussionCount": 7
  },
  {
    "meeting": 121,
    "dateISO": "2025-10-15",
    "timeUTC": "16:00",
    "title": "EIPIP Meeting #121, Oct 15, 2025",
    "issueUrl": "https://github.com/ethereum/pm/issues/1762",
    "repo": "ethereum/pm",
    "cfiCount": 0,
    "discussionCount": 10
  },
  {
    "meeting": 120,
    "dateISO": "2025-09-17",
    "timeUTC": "16:00",
    "title": "EIPIP Meeting 120 | Sep 17, 2025",
    "issueUrl": "https://github.com/ethereum/pm/issues/1727",
    "repo": "ethereum/pm",
    "cfiCount": 0,
    "discussionCount": 0
  },
  {
    "meeting": 119,
    "dateISO": "2025-08-20",
    "timeUTC": null,
    "title": "EIPIP Meeting 119 | Aug 20, 2025",
    "issueUrl": "https://github.com/ethereum/pm/issues/1628",
    "repo": "ethereum/pm",
    "cfiCount": 2,
    "discussionCount": 0
  },
  {
    "meeting": 118,
    "dateISO": "2025-07-16",
    "timeUTC": null,
    "title": "EIPIP Meeting 118 | July 16, 2025",
    "issueUrl": "https://github.com/ethereum/pm/issues/1621",
    "repo": "ethereum/pm",
    "cfiCount": 2,
    "discussionCount": 0
  },
  {
    "meeting": 117,
    "dateISO": "2025-06-18",
    "timeUTC": null,
    "title": "EIPIP Meeting 117 | June 18, 2025",
    "issueUrl": "https://github.com/ethereum/pm/issues/1580",
    "repo": "ethereum/pm",
    "cfiCount": 1,
    "discussionCount": 0
  },
  {
    "meeting": 116,
    "dateISO": "2025-05-21",
    "timeUTC": null,
    "title": "EIPIP Meeting 116 | May 21, 2025",
    "issueUrl": "https://github.com/ethereum/pm/issues/1483",
    "repo": "ethereum/pm",
    "cfiCount": 0,
    "discussionCount": 0
  },
  {
    "meeting": 115,
    "dateISO": "2025-04-16",
    "timeUTC": null,
    "title": "EIPIP Meeting 115 | April 16, 2025",
    "issueUrl": "https://github.com/ethereum/pm/issues/1402",
    "repo": "ethereum/pm",
    "cfiCount": 2,
    "discussionCount": 0
  },
  {
    "meeting": 114,
    "dateISO": "2025-03-19",
    "timeUTC": null,
    "title": "EIPIP Meeting 114 | March 19, 2025",
    "issueUrl": "https://github.com/ethereum/pm/issues/1331",
    "repo": "ethereum/pm",
    "cfiCount": 2,
    "discussionCount": 0
  },
  {
    "meeting": 113,
    "dateISO": "2025-01-16",
    "timeUTC": null,
    "title": "EIPIP Meeting 113",
    "issueUrl": "https://github.com/ethcatherders/EIPIP/issues/378",
    "repo": "ethcatherders/EIPIP",
    "cfiCount": 3,
    "discussionCount": 0
  },
  {
    "meeting": 112,
    "dateISO": "2024-12-19",
    "timeUTC": null,
    "title": "EIPIP Meeting 112",
    "issueUrl": "https://github.com/ethcatherders/EIPIP/issues/375",
    "repo": "ethcatherders/EIPIP",
    "cfiCount": 4,
    "discussionCount": 0
  },
  {
    "meeting": 111,
    "dateISO": "2024-10-16",
    "timeUTC": null,
    "title": "EIPIP Meeting 111",
    "issueUrl": "https://github.com/ethcatherders/EIPIP/issues/365",
    "repo": "ethcatherders/EIPIP",
    "cfiCount": 3,
    "discussionCount": 0
  },
  {
    "meeting": 110,
    "dateISO": "2024-09-25",
    "timeUTC": null,
    "title": "EIPIP Meeting 110",
    "issueUrl": "https://github.com/ethcatherders/EIPIP/issues/361",
    "repo": "ethcatherders/EIPIP",
    "cfiCount": 2,
    "discussionCount": 0
  },
  {
    "meeting": 109,
    "dateISO": "2024-08-21",
    "timeUTC": null,
    "title": "EIPIP Meeting 109",
    "issueUrl": "https://github.com/ethcatherders/EIPIP/issues/356",
    "repo": "ethcatherders/EIPIP",
    "cfiCount": 2,
    "discussionCount": 0
  },
  {
    "meeting": 108,
    "dateISO": "2024-07-19",
    "timeUTC": null,
    "title": "EIPIP Meeting 108",
    "issueUrl": "https://github.com/ethcatherders/EIPIP/issues/350",
    "repo": "ethcatherders/EIPIP",
    "cfiCount": 4,
    "discussionCount": 0
  },
  {
    "meeting": 107,
    "dateISO": "2024-07-04",
    "timeUTC": null,
    "title": "EIPIP Meeting 107",
    "issueUrl": "https://github.com/ethcatherders/EIPIP/issues/346",
    "repo": "ethcatherders/EIPIP",
    "cfiCount": 3,
    "discussionCount": 0
  },
  {
    "meeting": 106,
    "dateISO": "2024-06-06",
    "timeUTC": null,
    "title": "EIPIP Meeting 106",
    "issueUrl": "https://github.com/ethcatherders/EIPIP/issues/340",
    "repo": "ethcatherders/EIPIP",
    "cfiCount": 1,
    "discussionCount": 0
  },
  {
    "meeting": 105,
    "dateISO": "2024-05-22",
    "timeUTC": null,
    "title": "EIPIP Meeting 105",
    "issueUrl": "https://github.com/ethcatherders/EIPIP/issues/337",
    "repo": "ethcatherders/EIPIP",
    "cfiCount": 0,
    "discussionCount": 0
  },
  {
    "meeting": 104,
    "dateISO": "2024-04-25",
    "timeUTC": null,
    "title": "EIPIP Meeting 104",
    "issueUrl": "https://github.com/ethcatherders/EIPIP/issues/336",
    "repo": "ethcatherders/EIPIP",
    "cfiCount": 3,
    "discussionCount": 0
  },
  {
    "meeting": 103,
    "dateISO": "2024-04-11",
    "timeUTC": null,
    "title": "EIPIP Meeting 103",
    "issueUrl": "https://github.com/ethcatherders/EIPIP/issues/334",
    "repo": "ethcatherders/EIPIP",
    "cfiCount": 5,
    "discussionCount": 0
  },
  {
    "meeting": 102,
    "dateISO": "2024-03-13",
    "timeUTC": null,
    "title": "EIPIP Meeting 102",
    "issueUrl": "https://github.com/ethcatherders/EIPIP/issues/326",
    "repo": "ethcatherders/EIPIP",
    "cfiCount": 9,
    "discussionCount": 0
  },
  {
    "meeting": 101,
    "dateISO": "2024-02-15",
    "timeUTC": null,
    "title": "EIPIP Meeting 101",
    "issueUrl": "https://github.com/ethcatherders/EIPIP/issues/316",
    "repo": "ethcatherders/EIPIP",
    "cfiCount": 5,
    "discussionCount": 0
  },
  {
    "meeting": 100,
    "dateISO": "2024-02-07",
    "timeUTC": null,
    "title": "EIPIP Meeting 100",
    "issueUrl": "https://github.com/ethcatherders/EIPIP/issues/312",
    "repo": "ethcatherders/EIPIP",
    "cfiCount": 2,
    "discussionCount": 0
  },
  {
    "meeting": 99,
    "dateISO": "2024-01-18",
    "timeUTC": null,
    "title": "EIPIP Meeting 99",
    "issueUrl": "https://github.com/ethcatherders/EIPIP/issues/310",
    "repo": "ethcatherders/EIPIP",
    "cfiCount": 2,
    "discussionCount": 0
  },
  {
    "meeting": 98,
    "dateISO": "2024-01-03",
    "timeUTC": null,
    "title": "EIPIP Meeting 98",
    "issueUrl": "https://github.com/ethcatherders/EIPIP/issues/305",
    "repo": "ethcatherders/EIPIP",
    "cfiCount": 2,
    "discussionCount": 0
  },
  {
    "meeting": 97,
    "dateISO": "2023-12-13",
    "timeUTC": null,
    "title": "EIPIP Meeting 97",
    "issueUrl": "https://github.com/ethcatherders/EIPIP/issues/302",
    "repo": "ethcatherders/EIPIP",
    "cfiCount": 2,
    "discussionCount": 0
  },
  {
    "meeting": 96,
    "dateISO": "2023-11-29",
    "timeUTC": null,
    "title": "EIPIP Meeting 96",
    "issueUrl": "https://github.com/ethcatherders/EIPIP/issues/300",
    "repo": "ethcatherders/EIPIP",
    "cfiCount": 4,
    "discussionCount": 0
  },
  {
    "meeting": 95,
    "dateISO": "2023-11-15",
    "timeUTC": null,
    "title": "EIPIP Meeting 95",
    "issueUrl": "https://github.com/ethcatherders/EIPIP/issues/297",
    "repo": "ethcatherders/EIPIP",
    "cfiCount": 7,
    "discussionCount": 0
  },
  {
    "meeting": 94,
    "dateISO": "2023-11-01",
    "timeUTC": null,
    "title": "EIPIP Meeting 94",
    "issueUrl": "https://github.com/ethcatherders/EIPIP/issues/292",
    "repo": "ethcatherders/EIPIP",
    "cfiCount": 6,
    "discussionCount": 0
  },
  {
    "meeting": 93,
    "dateISO": "2023-10-18",
    "timeUTC": null,
    "title": "EIPIP Meeting 93",
    "issueUrl": "https://github.com/ethcatherders/EIPIP/issues/285",
    "repo": "ethcatherders/EIPIP",
    "cfiCount": 5,
    "discussionCount": 0
  },
  {
    "meeting": 92,
    "dateISO": "2023-10-04",
    "timeUTC": null,
    "title": "EIPIP Meeting 92",
    "issueUrl": "https://github.com/ethcatherders/EIPIP/issues/281",
    "repo": "ethcatherders/EIPIP",
    "cfiCount": 14,
    "discussionCount": 0
  },
  {
    "meeting": 91,
    "dateISO": "2023-09-20",
    "timeUTC": null,
    "title": "EIPIP Meeting 91",
    "issueUrl": "https://github.com/ethcatherders/EIPIP/issues/278",
    "repo": "ethcatherders/EIPIP",
    "cfiCount": 0,
    "discussionCount": 0
  },
  {
    "meeting": 90,
    "dateISO": "2023-09-06",
    "timeUTC": null,
    "title": "EIPIP Meeting 90",
    "issueUrl": "https://github.com/ethcatherders/EIPIP/issues/271",
    "repo": "ethcatherders/EIPIP",
    "cfiCount": 0,
    "discussionCount": 0
  },
  {
    "meeting": 89,
    "dateISO": "2023-08-24",
    "timeUTC": null,
    "title": "EIPIP Meeting 89",
    "issueUrl": "https://github.com/ethcatherders/EIPIP/issues/260",
    "repo": "ethcatherders/EIPIP",
    "cfiCount": 0,
    "discussionCount": 0
  },
  {
    "meeting": 88,
    "dateISO": "2023-08-10",
    "timeUTC": null,
    "title": "EIPIP Meeting 88",
    "issueUrl": "https://github.com/ethcatherders/EIPIP/issues/257",
    "repo": "ethcatherders/EIPIP",
    "cfiCount": 0,
    "discussionCount": 0
  },
  {
    "meeting": 87,
    "dateISO": "2023-07-26",
    "timeUTC": null,
    "title": "EIPIP Meeting 87",
    "issueUrl": "https://github.com/ethcatherders/EIPIP/issues/255",
    "repo": "ethcatherders/EIPIP",
    "cfiCount": 0,
    "discussionCount": 0
  },
  {
    "meeting": 86,
    "dateISO": "2023-07-12",
    "timeUTC": null,
    "title": "EIPIP Meeting 86",
    "issueUrl": "https://github.com/ethcatherders/EIPIP/issues/252",
    "repo": "ethcatherders/EIPIP",
    "cfiCount": 0,
    "discussionCount": 0
  },
  {
    "meeting": 85,
    "dateISO": "2023-06-28",
    "timeUTC": null,
    "title": "EIPIP Meeting 85",
    "issueUrl": "https://github.com/ethcatherders/EIPIP/issues/248",
    "repo": "ethcatherders/EIPIP",
    "cfiCount": 0,
    "discussionCount": 0
  },
  {
    "meeting": 84,
    "dateISO": "2023-06-14",
    "timeUTC": null,
    "title": "EIPIP Meeting 84",
    "issueUrl": "https://github.com/ethcatherders/EIPIP/issues/245",
    "repo": "ethcatherders/EIPIP",
    "cfiCount": 0,
    "discussionCount": 0
  },
  {
    "meeting": 83,
    "dateISO": "2023-05-31",
    "timeUTC": null,
    "title": "EIPIP Meeting 83",
    "issueUrl": "https://github.com/ethcatherders/EIPIP/issues/241",
    "repo": "ethcatherders/EIPIP",
    "cfiCount": 0,
    "discussionCount": 0
  },
  {
    "meeting": 82,
    "dateISO": "2023-05-18",
    "timeUTC": null,
    "title": "EIPIP Meeting 82",
    "issueUrl": "https://github.com/ethcatherders/EIPIP/issues/235",
    "repo": "ethcatherders/EIPIP",
    "cfiCount": 0,
    "discussionCount": 0
  },
  {
    "meeting": 81,
    "dateISO": "2023-05-03",
    "timeUTC": null,
    "title": "EIPIP Meeting 81",
    "issueUrl": "https://github.com/ethcatherders/EIPIP/issues/232",
    "repo": "ethcatherders/EIPIP",
    "cfiCount": 0,
    "discussionCount": 0
  },
  {
    "meeting": 80,
    "dateISO": "2023-04-20",
    "timeUTC": null,
    "title": "EIPIP Meeting 80",
    "issueUrl": "https://github.com/ethcatherders/EIPIP/issues/229",
    "repo": "ethcatherders/EIPIP",
    "cfiCount": 0,
    "discussionCount": 0
  },
  {
    "meeting": 79,
    "dateISO": "2023-04-05",
    "timeUTC": null,
    "title": "EIPIP Meeting 79",
    "issueUrl": "https://github.com/ethcatherders/EIPIP/issues/226",
    "repo": "ethcatherders/EIPIP",
    "cfiCount": 0,
    "discussionCount": 0
  },
  {
    "meeting": 78,
    "dateISO": "2023-03-31",
    "timeUTC": null,
    "title": "EIPIP Meeting 78",
    "issueUrl": "https://github.com/ethcatherders/EIPIP/issues/224",
    "repo": "ethcatherders/EIPIP",
    "cfiCount": 0,
    "discussionCount": 0
  },
  {
    "meeting": 77,
    "dateISO": "2023-03-16",
    "timeUTC": null,
    "title": "EIPIP Meeting 77",
    "issueUrl": "https://github.com/ethcatherders/EIPIP/issues/219",
    "repo": "ethcatherders/EIPIP",
    "cfiCount": 0,
    "discussionCount": 0
  },
  {
    "meeting": 76,
    "dateISO": "2023-03-19",
    "timeUTC": null,
    "title": "Funding for EIPIP Meeting 076",
    "issueUrl": "https://github.com/ethcatherders/EIPIP/issues/221",
    "repo": "ethcatherders/EIPIP",
    "cfiCount": 0,
    "discussionCount": 0
  },
  {
    "meeting": 75,
    "dateISO": "2023-02-09",
    "timeUTC": null,
    "title": "EIPIP Meeting 75",
    "issueUrl": "https://github.com/ethcatherders/EIPIP/issues/213",
    "repo": "ethcatherders/EIPIP",
    "cfiCount": 0,
    "discussionCount": 0
  },
  {
    "meeting": 74,
    "dateISO": "2023-01-25",
    "timeUTC": null,
    "title": "EIPIP Meeting 74",
    "issueUrl": "https://github.com/ethcatherders/EIPIP/issues/210",
    "repo": "ethcatherders/EIPIP",
    "cfiCount": 0,
    "discussionCount": 0
  },
  {
    "meeting": 73,
    "dateISO": "2023-01-11",
    "timeUTC": null,
    "title": "EIPIP Meeting 73",
    "issueUrl": "https://github.com/ethcatherders/EIPIP/issues/208",
    "repo": "ethcatherders/EIPIP",
    "cfiCount": 0,
    "discussionCount": 0
  },
  {
    "meeting": 72,
    "dateISO": "2022-12-14",
    "timeUTC": null,
    "title": "EIPIP Meeting 72",
    "issueUrl": "https://github.com/ethcatherders/EIPIP/issues/202",
    "repo": "ethcatherders/EIPIP",
    "cfiCount": 0,
    "discussionCount": 0
  },
  {
    "meeting": 71,
    "dateISO": "2022-12-12",
    "timeUTC": null,
    "title": "EIPIP Meeting 71 Agenda",
    "issueUrl": "https://github.com/ethcatherders/EIPIP/issues/198",
    "repo": "ethcatherders/EIPIP",
    "cfiCount": 0,
    "discussionCount": 0
  },
  {
    "meeting": 70,
    "dateISO": "2022-11-16",
    "timeUTC": null,
    "title": "EIPIP Meeting 70 Agenda",
    "issueUrl": "https://github.com/ethcatherders/EIPIP/issues/195",
    "repo": "ethcatherders/EIPIP",
    "cfiCount": 0,
    "discussionCount": 0
  },
  {
    "meeting": 69,
    "dateISO": "2022-11-11",
    "timeUTC": null,
    "title": "EIPIP Meeting 69 Agenda",
    "issueUrl": "https://github.com/ethcatherders/EIPIP/issues/192",
    "repo": "ethcatherders/EIPIP",
    "cfiCount": 0,
    "discussionCount": 0
  },
  {
    "meeting": 68,
    "dateISO": "2022-10-20",
    "timeUTC": null,
    "title": "EIPIP Meeting 68 Agenda",
    "issueUrl": "https://github.com/ethcatherders/EIPIP/issues/187",
    "repo": "ethcatherders/EIPIP",
    "cfiCount": 0,
    "discussionCount": 0
  },
  {
    "meeting": 67,
    "dateISO": "2022-10-17",
    "timeUTC": null,
    "title": "EIPIP Meeting 67 Agenda",
    "issueUrl": "https://github.com/ethcatherders/EIPIP/issues/185",
    "repo": "ethcatherders/EIPIP",
    "cfiCount": 0,
    "discussionCount": 0
  },
  {
    "meeting": 66,
    "dateISO": "2022-09-21",
    "timeUTC": null,
    "title": "EIPIP Meeting 66 Agenda",
    "issueUrl": "https://github.com/ethcatherders/EIPIP/issues/181",
    "repo": "ethcatherders/EIPIP",
    "cfiCount": 0,
    "discussionCount": 0
  },
  {
    "meeting": 65,
    "dateISO": "2022-09-16",
    "timeUTC": null,
    "title": "EIPIP Meeting 65 Agenda",
    "issueUrl": "https://github.com/ethcatherders/EIPIP/issues/176",
    "repo": "ethcatherders/EIPIP",
    "cfiCount": 0,
    "discussionCount": 0
  },
  {
    "meeting": 64,
    "dateISO": "2022-08-24",
    "timeUTC": null,
    "title": "EIPIP Meeting 64 Agenda",
    "issueUrl": "https://github.com/ethcatherders/EIPIP/issues/174",
    "repo": "ethcatherders/EIPIP",
    "cfiCount": 0,
    "discussionCount": 0
  },
  {
    "meeting": 63,
    "dateISO": "2022-08-10",
    "timeUTC": null,
    "title": "EIPIP Meeting 63 Agenda",
    "issueUrl": "https://github.com/ethcatherders/EIPIP/issues/170",
    "repo": "ethcatherders/EIPIP",
    "cfiCount": 0,
    "discussionCount": 0
  },
  {
    "meeting": 62,
    "dateISO": "2022-08-08",
    "timeUTC": null,
    "title": "EIPIP Meeting 62 Agenda",
    "issueUrl": "https://github.com/ethcatherders/EIPIP/issues/168",
    "repo": "ethcatherders/EIPIP",
    "cfiCount": 0,
    "discussionCount": 0
  },
  {
    "meeting": 61,
    "dateISO": "2022-07-14",
    "timeUTC": null,
    "title": "EIPIP Meeting 61 Agenda",
    "issueUrl": "https://github.com/ethcatherders/EIPIP/issues/161",
    "repo": "ethcatherders/EIPIP",
    "cfiCount": 0,
    "discussionCount": 0
  },
  {
    "meeting": 60,
    "dateISO": "2022-06-29",
    "timeUTC": null,
    "title": "EIPIP Meeting 60 Agenda",
    "issueUrl": "https://github.com/ethcatherders/EIPIP/issues/153",
    "repo": "ethcatherders/EIPIP",
    "cfiCount": 0,
    "discussionCount": 0
  },
  {
    "meeting": 59,
    "dateISO": "2022-06-29",
    "timeUTC": null,
    "title": "EIPIP Meeting 59 Agenda",
    "issueUrl": "https://github.com/ethcatherders/EIPIP/issues/152",
    "repo": "ethcatherders/EIPIP",
    "cfiCount": 0,
    "discussionCount": 0
  },
  {
    "meeting": 58,
    "dateISO": "2022-06-15",
    "timeUTC": null,
    "title": "EIPIP Meeting 58 Agenda",
    "issueUrl": "https://github.com/ethcatherders/EIPIP/issues/146",
    "repo": "ethcatherders/EIPIP",
    "cfiCount": 0,
    "discussionCount": 0
  },
  {
    "meeting": 57,
    "dateISO": "2022-06-01",
    "timeUTC": null,
    "title": "EIPIP Meeting 57 Agenda",
    "issueUrl": "https://github.com/ethcatherders/EIPIP/issues/141",
    "repo": "ethcatherders/EIPIP",
    "cfiCount": 0,
    "discussionCount": 0
  },
  {
    "meeting": 56,
    "dateISO": "2022-05-09",
    "timeUTC": null,
    "title": "EIPIP Meeting 56 Agenda",
    "issueUrl": "https://github.com/ethcatherders/EIPIP/issues/136",
    "repo": "ethcatherders/EIPIP",
    "cfiCount": 0,
    "discussionCount": 0
  },
  {
    "meeting": 55,
    "dateISO": "2022-04-27",
    "timeUTC": null,
    "title": "EIPIP Meeting 55 Agenda",
    "issueUrl": "https://github.com/ethcatherders/EIPIP/issues/130",
    "repo": "ethcatherders/EIPIP",
    "cfiCount": 0,
    "discussionCount": 0
  },
  {
    "meeting": 54,
    "dateISO": "2022-04-06",
    "timeUTC": null,
    "title": "EIPIP Meeting 54 Agenda",
    "issueUrl": "https://github.com/ethcatherders/EIPIP/issues/125",
    "repo": "ethcatherders/EIPIP",
    "cfiCount": 0,
    "discussionCount": 0
  },
  {
    "meeting": 53,
    "dateISO": "2022-03-23",
    "timeUTC": null,
    "title": "EIPIP Meeting 53 Agenda",
    "issueUrl": "https://github.com/ethcatherders/EIPIP/issues/118",
    "repo": "ethcatherders/EIPIP",
    "cfiCount": 0,
    "discussionCount": 0
  },
  {
    "meeting": 52,
    "dateISO": "2022-03-18",
    "timeUTC": null,
    "title": "EIPIP Meeting 52 Agenda",
    "issueUrl": "https://github.com/ethcatherders/EIPIP/issues/116",
    "repo": "ethcatherders/EIPIP",
    "cfiCount": 0,
    "discussionCount": 0
  },
  {
    "meeting": 51,
    "dateISO": "2022-02-23",
    "timeUTC": null,
    "title": "EIPIP Meeting 51 Agenda",
    "issueUrl": "https://github.com/ethcatherders/EIPIP/issues/112",
    "repo": "ethcatherders/EIPIP",
    "cfiCount": 0,
    "discussionCount": 0
  },
  {
    "meeting": 50,
    "dateISO": "2022-02-09",
    "timeUTC": null,
    "title": "EIPIP Meeting 50 Agenda",
    "issueUrl": "https://github.com/ethcatherders/EIPIP/issues/110",
    "repo": "ethcatherders/EIPIP",
    "cfiCount": 0,
    "discussionCount": 0
  },
  {
    "meeting": 49,
    "dateISO": "2022-01-26",
    "timeUTC": null,
    "title": "EIPIP Meeting 49 Agenda",
    "issueUrl": "https://github.com/ethcatherders/EIPIP/issues/107",
    "repo": "ethcatherders/EIPIP",
    "cfiCount": 0,
    "discussionCount": 0
  },
  {
    "meeting": 48,
    "dateISO": "2022-01-24",
    "timeUTC": null,
    "title": "EIPIP Meeting 48 Agenda",
    "issueUrl": "https://github.com/ethcatherders/EIPIP/issues/105",
    "repo": "ethcatherders/EIPIP",
    "cfiCount": 0,
    "discussionCount": 0
  },
  {
    "meeting": 47,
    "dateISO": "2021-12-28",
    "timeUTC": null,
    "title": "EIPIP Meeting 47 Agenda",
    "issueUrl": "https://github.com/ethcatherders/EIPIP/issues/101",
    "repo": "ethcatherders/EIPIP",
    "cfiCount": 0,
    "discussionCount": 0
  },
  {
    "meeting": 46,
    "dateISO": "2021-12-07",
    "timeUTC": null,
    "title": "EIPIP Meeting 46 Agenda",
    "issueUrl": "https://github.com/ethcatherders/EIPIP/issues/98",
    "repo": "ethcatherders/EIPIP",
    "cfiCount": 0,
    "discussionCount": 0
  },
  {
    "meeting": 45,
    "dateISO": "2021-11-30",
    "timeUTC": null,
    "title": "EIPIP Meeting 45 Agenda",
    "issueUrl": "https://github.com/ethcatherders/EIPIP/issues/95",
    "repo": "ethcatherders/EIPIP",
    "cfiCount": 0,
    "discussionCount": 0
  },
  {
    "meeting": 44,
    "dateISO": "2021-11-05",
    "timeUTC": null,
    "title": "EIPIP Meeting 44 Agenda",
    "issueUrl": "https://github.com/ethcatherders/EIPIP/issues/91",
    "repo": "ethcatherders/EIPIP",
    "cfiCount": 0,
    "discussionCount": 0
  },
  {
    "meeting": 43,
    "dateISO": "2021-10-28",
    "timeUTC": null,
    "title": "EIPIP Meeting 43 Agenda",
    "issueUrl": "https://github.com/ethcatherders/EIPIP/issues/90",
    "repo": "ethcatherders/EIPIP",
    "cfiCount": 0,
    "discussionCount": 0
  },
  {
    "meeting": 42,
    "dateISO": "2021-09-22",
    "timeUTC": null,
    "title": "EIPIP Meeting 42 Agenda",
    "issueUrl": "https://github.com/ethcatherders/EIPIP/issues/87",
    "repo": "ethcatherders/EIPIP",
    "cfiCount": 0,
    "discussionCount": 0
  },
  {
    "meeting": 41,
    "dateISO": "2021-08-25",
    "timeUTC": null,
    "title": "EIPIP Meeting 41 Agenda",
    "issueUrl": "https://github.com/ethcatherders/EIPIP/issues/85",
    "repo": "ethcatherders/EIPIP",
    "cfiCount": 0,
    "discussionCount": 0
  },
  {
    "meeting": 40,
    "dateISO": "2021-08-11",
    "timeUTC": null,
    "title": "EIPIP Meeting 40 Agenda",
    "issueUrl": "https://github.com/ethcatherders/EIPIP/issues/83",
    "repo": "ethcatherders/EIPIP",
    "cfiCount": 0,
    "discussionCount": 0
  },
  {
    "meeting": 39,
    "dateISO": "2021-08-11",
    "timeUTC": null,
    "title": "EIPIP Meeting 39 Agenda",
    "issueUrl": "https://github.com/ethcatherders/EIPIP/issues/82",
    "repo": "ethcatherders/EIPIP",
    "cfiCount": 0,
    "discussionCount": 0
  },
  {
    "meeting": 38,
    "dateISO": "2021-07-14",
    "timeUTC": null,
    "title": "EIPIP Meeting 38 Agenda",
    "issueUrl": "https://github.com/ethcatherders/EIPIP/issues/79",
    "repo": "ethcatherders/EIPIP",
    "cfiCount": 0,
    "discussionCount": 0
  },
  {
    "meeting": 37,
    "dateISO": "2021-07-09",
    "timeUTC": null,
    "title": "EIPIP Meeting 37 Agenda",
    "issueUrl": "https://github.com/ethcatherders/EIPIP/issues/78",
    "repo": "ethcatherders/EIPIP",
    "cfiCount": 0,
    "discussionCount": 0
  },
  {
    "meeting": 36,
    "dateISO": "2021-06-17",
    "timeUTC": null,
    "title": "EIPIP Meeting 36 Agenda",
    "issueUrl": "https://github.com/ethcatherders/EIPIP/issues/75",
    "repo": "ethcatherders/EIPIP",
    "cfiCount": 0,
    "discussionCount": 0
  },
  {
    "meeting": 35,
    "dateISO": "2021-06-02",
    "timeUTC": null,
    "title": "EIPIP Meeting 35 Agenda",
    "issueUrl": "https://github.com/ethcatherders/EIPIP/issues/72",
    "repo": "ethcatherders/EIPIP",
    "cfiCount": 0,
    "discussionCount": 0
  },
  {
    "meeting": 34,
    "dateISO": "2021-05-24",
    "timeUTC": null,
    "title": "EIPIP Meeting 34 Agenda",
    "issueUrl": "https://github.com/ethcatherders/EIPIP/issues/70",
    "repo": "ethcatherders/EIPIP",
    "cfiCount": 0,
    "discussionCount": 0
  },
  {
    "meeting": 33,
    "dateISO": "2021-05-14",
    "timeUTC": null,
    "title": "EIPIP Meeting 33 Agenda",
    "issueUrl": "https://github.com/ethcatherders/EIPIP/issues/69",
    "repo": "ethcatherders/EIPIP",
    "cfiCount": 0,
    "discussionCount": 0
  },
  {
    "meeting": 32,
    "dateISO": "2021-04-30",
    "timeUTC": null,
    "title": "EIPIP Meeting 32 Agenda",
    "issueUrl": "https://github.com/ethcatherders/EIPIP/issues/67",
    "repo": "ethcatherders/EIPIP",
    "cfiCount": 0,
    "discussionCount": 0
  },
  {
    "meeting": 31,
    "dateISO": "2021-04-19",
    "timeUTC": null,
    "title": "EIPIP Meeting 31 Agenda",
    "issueUrl": "https://github.com/ethcatherders/EIPIP/issues/65",
    "repo": "ethcatherders/EIPIP",
    "cfiCount": 0,
    "discussionCount": 0
  },
  {
    "meeting": 30,
    "dateISO": "2021-03-25",
    "timeUTC": null,
    "title": "EIPIP Meeting 30 Agenda",
    "issueUrl": "https://github.com/ethcatherders/EIPIP/issues/62",
    "repo": "ethcatherders/EIPIP",
    "cfiCount": 0,
    "discussionCount": 0
  },
  {
    "meeting": 29,
    "dateISO": "2021-03-10",
    "timeUTC": null,
    "title": "EIPIP Meeting 29 Agenda",
    "issueUrl": "https://github.com/ethcatherders/EIPIP/issues/57",
    "repo": "ethcatherders/EIPIP",
    "cfiCount": 0,
    "discussionCount": 0
  },
  {
    "meeting": 28,
    "dateISO": "2021-03-05",
    "timeUTC": null,
    "title": "EIPIP Meeting 28 Agenda",
    "issueUrl": "https://github.com/ethcatherders/EIPIP/issues/56",
    "repo": "ethcatherders/EIPIP",
    "cfiCount": 0,
    "discussionCount": 0
  },
  {
    "meeting": 27,
    "dateISO": "2021-02-21",
    "timeUTC": null,
    "title": "EIPIP Meeting 27 Agenda",
    "issueUrl": "https://github.com/ethcatherders/EIPIP/issues/54",
    "repo": "ethcatherders/EIPIP",
    "cfiCount": 0,
    "discussionCount": 0
  },
  {
    "meeting": 26,
    "dateISO": "2021-01-27",
    "timeUTC": null,
    "title": "EIPIP Meeting 26 Agenda",
    "issueUrl": "https://github.com/ethcatherders/EIPIP/issues/50",
    "repo": "ethcatherders/EIPIP",
    "cfiCount": 0,
    "discussionCount": 0
  },
  {
    "meeting": 25,
    "dateISO": "2021-01-13",
    "timeUTC": null,
    "title": "EIPIP Meeting 25 Agenda",
    "issueUrl": "https://github.com/ethcatherders/EIPIP/issues/48",
    "repo": "ethcatherders/EIPIP",
    "cfiCount": 0,
    "discussionCount": 0
  },
  {
    "meeting": 24,
    "dateISO": "2020-12-20",
    "timeUTC": null,
    "title": "EIPIP Meeting 24 Agenda",
    "issueUrl": "https://github.com/ethcatherders/EIPIP/issues/47",
    "repo": "ethcatherders/EIPIP",
    "cfiCount": 0,
    "discussionCount": 0
  },
  {
    "meeting": 23,
    "dateISO": "2020-12-02",
    "timeUTC": null,
    "title": "EIPIP Meeting 23 Agenda",
    "issueUrl": "https://github.com/ethcatherders/EIPIP/issues/44",
    "repo": "ethcatherders/EIPIP",
    "cfiCount": 0,
    "discussionCount": 0
  },
  {
    "meeting": 22,
    "dateISO": "2020-11-30",
    "timeUTC": null,
    "title": "EIPIP Meeting 22 Agenda",
    "issueUrl": "https://github.com/ethcatherders/EIPIP/issues/43",
    "repo": "ethcatherders/EIPIP",
    "cfiCount": 0,
    "discussionCount": 0
  },
  {
    "meeting": 21,
    "dateISO": "2020-11-05",
    "timeUTC": null,
    "title": "EIPIP Meeting 21 Agenda",
    "issueUrl": "https://github.com/ethcatherders/EIPIP/issues/39",
    "repo": "ethcatherders/EIPIP",
    "cfiCount": 0,
    "discussionCount": 0
  },
  {
    "meeting": 20,
    "dateISO": "2020-10-23",
    "timeUTC": null,
    "title": "EIPIP Meeting 20 Agenda",
    "issueUrl": "https://github.com/ethcatherders/EIPIP/issues/38",
    "repo": "ethcatherders/EIPIP",
    "cfiCount": 0,
    "discussionCount": 0
  },
  {
    "meeting": 19,
    "dateISO": "2020-10-07",
    "timeUTC": null,
    "title": "EIPIP Meeting 19 Agenda",
    "issueUrl": "https://github.com/ethcatherders/EIPIP/issues/36",
    "repo": "ethcatherders/EIPIP",
    "cfiCount": 0,
    "discussionCount": 0
  },
  {
    "meeting": 18,
    "dateISO": "2020-09-28",
    "timeUTC": null,
    "title": "EIPIP Meeting 18 Agenda",
    "issueUrl": "https://github.com/ethcatherders/EIPIP/issues/34",
    "repo": "ethcatherders/EIPIP",
    "cfiCount": 0,
    "discussionCount": 0
  },
  {
    "meeting": 17,
    "dateISO": "2020-09-17",
    "timeUTC": null,
    "title": "EIPIP Meeting 17 Agenda",
    "issueUrl": "https://github.com/ethcatherders/EIPIP/issues/33",
    "repo": "ethcatherders/EIPIP",
    "cfiCount": 0,
    "discussionCount": 0
  },
  {
    "meeting": 16,
    "dateISO": "2020-08-28",
    "timeUTC": null,
    "title": "EIPIP Meeting 16 Agenda",
    "issueUrl": "https://github.com/ethcatherders/EIPIP/issues/30",
    "repo": "ethcatherders/EIPIP",
    "cfiCount": 0,
    "discussionCount": 0
  },
  {
    "meeting": 15,
    "dateISO": "2020-08-22",
    "timeUTC": null,
    "title": "EIPIP Meeting 15 Agenda",
    "issueUrl": "https://github.com/ethcatherders/EIPIP/issues/29",
    "repo": "ethcatherders/EIPIP",
    "cfiCount": 0,
    "discussionCount": 0
  },
  {
    "meeting": 14,
    "dateISO": "2020-08-07",
    "timeUTC": null,
    "title": "EIPIP Meeting 14 Agenda",
    "issueUrl": "https://github.com/ethcatherders/EIPIP/issues/26",
    "repo": "ethcatherders/EIPIP",
    "cfiCount": 0,
    "discussionCount": 0
  },
  {
    "meeting": 13,
    "dateISO": "2020-07-20",
    "timeUTC": null,
    "title": "EIPIP Meeting 13 Agenda",
    "issueUrl": "https://github.com/ethcatherders/EIPIP/issues/25",
    "repo": "ethcatherders/EIPIP",
    "cfiCount": 0,
    "discussionCount": 0
  },
  {
    "meeting": 12,
    "dateISO": "2020-07-13",
    "timeUTC": null,
    "title": "EIPIP Meeting 12 Agenda",
    "issueUrl": "https://github.com/ethcatherders/EIPIP/issues/23",
    "repo": "ethcatherders/EIPIP",
    "cfiCount": 0,
    "discussionCount": 0
  },
  {
    "meeting": 11,
    "dateISO": "2020-06-25",
    "timeUTC": null,
    "title": "EIPIP Meeting 11 Agenda",
    "issueUrl": "https://github.com/ethcatherders/EIPIP/issues/21",
    "repo": "ethcatherders/EIPIP",
    "cfiCount": 0,
    "discussionCount": 0
  },
  {
    "meeting": 10,
    "dateISO": "2020-06-05",
    "timeUTC": null,
    "title": "EIPIP Meeting 10 Agenda",
    "issueUrl": "https://github.com/ethcatherders/EIPIP/issues/19",
    "repo": "ethcatherders/EIPIP",
    "cfiCount": 0,
    "discussionCount": 0
  },
  {
    "meeting": 9,
    "dateISO": "2020-05-21",
    "timeUTC": null,
    "title": "EIPIP Meeting 9 Agenda",
    "issueUrl": "https://github.com/ethcatherders/EIPIP/issues/16",
    "repo": "ethcatherders/EIPIP",
    "cfiCount": 0,
    "discussionCount": 0
  },
  {
    "meeting": 8,
    "dateISO": "2020-05-15",
    "timeUTC": null,
    "title": "EIPIP Meeting 8 Agenda",
    "issueUrl": "https://github.com/ethcatherders/EIPIP/issues/15",
    "repo": "ethcatherders/EIPIP",
    "cfiCount": 0,
    "discussionCount": 0
  },
  {
    "meeting": 7,
    "dateISO": "2020-05-02",
    "timeUTC": null,
    "title": "EIPIP Meeting 7 Agenda",
    "issueUrl": "https://github.com/ethcatherders/EIPIP/issues/13",
    "repo": "ethcatherders/EIPIP",
    "cfiCount": 0,
    "discussionCount": 0
  },
  {
    "meeting": 6,
    "dateISO": "2020-03-23",
    "timeUTC": null,
    "title": "EIPIP Meeting 6 Agenda",
    "issueUrl": "https://github.com/ethcatherders/EIPIP/issues/10",
    "repo": "ethcatherders/EIPIP",
    "cfiCount": 0,
    "discussionCount": 0
  },
  {
    "meeting": 5,
    "dateISO": "2020-03-10",
    "timeUTC": null,
    "title": "EIPIP Meeting 5 Agenda",
    "issueUrl": "https://github.com/ethcatherders/EIPIP/issues/8",
    "repo": "ethcatherders/EIPIP",
    "cfiCount": 0,
    "discussionCount": 0
  },
  {
    "meeting": 4,
    "dateISO": "2020-02-25",
    "timeUTC": null,
    "title": "EIPIP Meeting 4 Agenda",
    "issueUrl": "https://github.com/ethcatherders/EIPIP/issues/6",
    "repo": "ethcatherders/EIPIP",
    "cfiCount": 0,
    "discussionCount": 0
  },
  {
    "meeting": 3,
    "dateISO": "2020-02-11",
    "timeUTC": null,
    "title": "EIPIP Meeting 3 Agenda",
    "issueUrl": "https://github.com/ethcatherders/EIPIP/issues/5",
    "repo": "ethcatherders/EIPIP",
    "cfiCount": 0,
    "discussionCount": 0
  },
  {
    "meeting": 2,
    "dateISO": "2020-01-18",
    "timeUTC": null,
    "title": "EIPIP Meeting 2 Agenda",
    "issueUrl": "https://github.com/ethcatherders/EIPIP/issues/1",
    "repo": "ethcatherders/EIPIP",
    "cfiCount": 0,
    "discussionCount": 0
  }
];
