// AUTO-GENERATED by scripts/backfill-office-hours.ts — do not edit by hand.
// Source: ethereum/pm issues titled "EIP Editing Office Hour ... Meeting #N".
// Regenerate: GITHUB_ACCESS_TOKEN=... npx tsx scripts/backfill-office-hours.ts

export type OfficeHourMeeting = {
  meeting: number;
  dateISO: string;   // yyyy-mm-dd (final/rescheduled date)
  timeUTC: string | null; // "HH:MM" in UTC, or null if unstated
  title: string;
  issueUrl: string;
};

export const OFFICE_HOUR_MEETINGS: OfficeHourMeeting[] = [
  {
    "meeting": 112,
    "dateISO": "2026-09-01",
    "timeUTC": "16:00",
    "title": "EIP Editing Office Hour (EIP + ERC ) Meeting #112, Sep 01, 2026",
    "issueUrl": "https://github.com/ethereum/pm/issues/2202"
  },
  {
    "meeting": 111,
    "dateISO": "2026-08-25",
    "timeUTC": "16:00",
    "title": "EIP Editing Office Hour (EIP + ERC ) Meeting #111, Aug 25, 2026",
    "issueUrl": "https://github.com/ethereum/pm/issues/2192"
  },
  {
    "meeting": 110,
    "dateISO": "2026-08-11",
    "timeUTC": "16:00",
    "title": "EIP Editing Office Hour (EIP + ERC ) Meeting #110, Aug 11, 2026",
    "issueUrl": "https://github.com/ethereum/pm/issues/2183"
  },
  {
    "meeting": 109,
    "dateISO": "2026-08-04",
    "timeUTC": "16:00",
    "title": "EIP Editing Office Hour (EIP + ERC ) Meeting #109, Aug 04, 2026",
    "issueUrl": "https://github.com/ethereum/pm/issues/2180"
  },
  {
    "meeting": 108,
    "dateISO": "2026-07-28",
    "timeUTC": "16:00",
    "title": "EIP Editing Office Hour (EIP + ERC ) Meeting #108, July 28, 2026",
    "issueUrl": "https://github.com/ethereum/pm/issues/2173"
  },
  {
    "meeting": 107,
    "dateISO": "2026-07-21",
    "timeUTC": "16:00",
    "title": "EIP Editing Office Hour (EIP + ERC ) Meeting #107, July 21, 2026",
    "issueUrl": "https://github.com/ethereum/pm/issues/2160"
  },
  {
    "meeting": 106,
    "dateISO": "2026-07-14",
    "timeUTC": "16:00",
    "title": "EIP Editing Office Hour (EIP + ERC ) Meeting #106, July 14, 2026",
    "issueUrl": "https://github.com/ethereum/pm/issues/2156"
  },
  {
    "meeting": 105,
    "dateISO": "2026-07-07",
    "timeUTC": "16:00",
    "title": "EIP Editing Office Hour (EIP + ERC ) Meeting #105, July 7, 2026",
    "issueUrl": "https://github.com/ethereum/pm/issues/2150"
  },
  {
    "meeting": 104,
    "dateISO": "2026-06-30",
    "timeUTC": "16:00",
    "title": "EIP Editing Office Hour (EIP + ERC ) Meeting #104, June 30, 2026",
    "issueUrl": "https://github.com/ethereum/pm/issues/2143"
  },
  {
    "meeting": 103,
    "dateISO": "2026-06-23",
    "timeUTC": "16:00",
    "title": "EIP Editing Office Hour (EIP + ERC ) Meeting #103, June 23, 2026",
    "issueUrl": "https://github.com/ethereum/pm/issues/2134"
  },
  {
    "meeting": 102,
    "dateISO": "2026-06-16",
    "timeUTC": "16:00",
    "title": "EIP Editing Office Hour (EIP + ERC ) Meeting #102, June 16, 2026",
    "issueUrl": "https://github.com/ethereum/pm/issues/2123"
  },
  {
    "meeting": 101,
    "dateISO": "2026-06-09",
    "timeUTC": "16:00",
    "title": "EIP Editing Office Hour (EIP + ERC ) Meeting #101, June 09, 2026",
    "issueUrl": "https://github.com/ethereum/pm/issues/2108"
  },
  {
    "meeting": 100,
    "dateISO": "2026-06-02",
    "timeUTC": "16:00",
    "title": "EIP Editing Office Hour (EIP + ERC ) Meeting #100, June 02, 2026",
    "issueUrl": "https://github.com/ethereum/pm/issues/2080"
  },
  {
    "meeting": 99,
    "dateISO": "2026-05-12",
    "timeUTC": "16:00",
    "title": "EIP Editing Office Hour (EIP + ERC ) Meeting #99, May 12, 2026",
    "issueUrl": "https://github.com/ethereum/pm/issues/2043"
  },
  {
    "meeting": 98,
    "dateISO": "2026-05-05",
    "timeUTC": "16:00",
    "title": "EIP Editing Office Hour (EIP + ERC ) Meeting #98, May 05, 2026",
    "issueUrl": "https://github.com/ethereum/pm/issues/2039"
  },
  {
    "meeting": 97,
    "dateISO": "2026-04-14",
    "timeUTC": "16:00",
    "title": "EIP Editing Office Hour (EIP + ERC ) Meeting #97, April 14, 2026",
    "issueUrl": "https://github.com/ethereum/pm/issues/2017"
  },
  {
    "meeting": 96,
    "dateISO": "2026-04-07",
    "timeUTC": "16:00",
    "title": "EIP Editing Office Hour (EIP + ERC ) Meeting #96, April 07, 2026",
    "issueUrl": "https://github.com/ethereum/pm/issues/2007"
  },
  {
    "meeting": 95,
    "dateISO": "2026-03-31",
    "timeUTC": "16:00",
    "title": "EIP Editing Office Hour (EIP + ERC ) Meeting #95, March 31, 2026",
    "issueUrl": "https://github.com/ethereum/pm/issues/1994"
  },
  {
    "meeting": 94,
    "dateISO": "2026-03-24",
    "timeUTC": "16:00",
    "title": "EIP Editing Office Hour (EIP + ERC ) Meeting #94, March 24, 2026",
    "issueUrl": "https://github.com/ethereum/pm/issues/1986"
  },
  {
    "meeting": 93,
    "dateISO": "2026-03-17",
    "timeUTC": "16:00",
    "title": "EIP Editing Office Hour (EIP Only ) Meeting #93, March 17, 2026",
    "issueUrl": "https://github.com/ethereum/pm/issues/1972"
  },
  {
    "meeting": 92,
    "dateISO": "2026-03-10",
    "timeUTC": "16:00",
    "title": "EIP Editing Office Hour (EIP + ERC ) Meeting #92, March 10, 2026",
    "issueUrl": "https://github.com/ethereum/pm/issues/1961"
  },
  {
    "meeting": 91,
    "dateISO": "2026-03-03",
    "timeUTC": "16:00",
    "title": "EIP Editing Office Hour (EIP + ERC ) Meeting #91, March 03, 2026",
    "issueUrl": "https://github.com/ethereum/pm/issues/1957"
  },
  {
    "meeting": 90,
    "dateISO": "2026-02-24",
    "timeUTC": "16:00",
    "title": "EIP Editing Office Hour (EIP + ERC ) Meeting #90, Feb 24, 2026",
    "issueUrl": "https://github.com/ethereum/pm/issues/1933"
  },
  {
    "meeting": 89,
    "dateISO": "2026-02-17",
    "timeUTC": "16:00",
    "title": "EIP Editing Office Hour (EIP Only) Meeting #89, Feb 17, 2026",
    "issueUrl": "https://github.com/ethereum/pm/issues/1928"
  },
  {
    "meeting": 88,
    "dateISO": "2026-02-10",
    "timeUTC": "16:00",
    "title": "EIP Editing Office Hour (EIP + ERC) Meeting #88, Feb 10, 2026",
    "issueUrl": "https://github.com/ethereum/pm/issues/1912"
  },
  {
    "meeting": 87,
    "dateISO": "2026-02-03",
    "timeUTC": "16:00",
    "title": "EIP Editing Office Hour (EIP + ERC) Meeting #87",
    "issueUrl": "https://github.com/ethereum/pm/issues/1906"
  },
  {
    "meeting": 86,
    "dateISO": "2026-01-27",
    "timeUTC": "16:00",
    "title": "EIP Editing Office Hour (EIP + ERC) Meeting #86, Jan 27, 2026",
    "issueUrl": "https://github.com/ethereum/pm/issues/1885"
  },
  {
    "meeting": 85,
    "dateISO": "2026-01-20",
    "timeUTC": "16:00",
    "title": "EIP Editing Office Hour (EIP Only) Meeting #85, Jan 20, 2026",
    "issueUrl": "https://github.com/ethereum/pm/issues/1884"
  },
  {
    "meeting": 84,
    "dateISO": "2026-01-13",
    "timeUTC": "16:00",
    "title": "EIP Editing Office Hour (EIP + ERC) Meeting #84, Jan 13, 2026",
    "issueUrl": "https://github.com/ethereum/pm/issues/1872"
  },
  {
    "meeting": 83,
    "dateISO": "2026-01-06",
    "timeUTC": "16:00",
    "title": "EIP Editing Office Hour (EIP + ERC) Meeting #83, Jan 06, 2026",
    "issueUrl": "https://github.com/ethereum/pm/issues/1856"
  },
  {
    "meeting": 82,
    "dateISO": "2025-12-16",
    "timeUTC": "16:00",
    "title": "EIP Editing Office Hour (EIP + ERC) Meeting #82, Dec 16, 2025",
    "issueUrl": "https://github.com/ethereum/pm/issues/1839"
  },
  {
    "meeting": 81,
    "dateISO": "2025-12-09",
    "timeUTC": "16:00",
    "title": "EIP Editing Office Hour (EIP Only) Meeting #81, Dec 09, 2025",
    "issueUrl": "https://github.com/ethereum/pm/issues/1831"
  },
  {
    "meeting": 80,
    "dateISO": "2025-12-02",
    "timeUTC": "16:00",
    "title": "EIP Editing Office Hour (EIP + ERC) Meeting #80, Dec 02, 2025",
    "issueUrl": "https://github.com/ethereum/pm/issues/1829"
  },
  {
    "meeting": 79,
    "dateISO": "2025-11-11",
    "timeUTC": "16:00",
    "title": "EIP Editing Office Hour (EIP only) Meeting #79, Nov 11, 2025",
    "issueUrl": "https://github.com/ethereum/pm/issues/1809"
  },
  {
    "meeting": 78,
    "dateISO": "2025-11-04",
    "timeUTC": "16:00",
    "title": "EIP Editing Office Hour (EIP + ERC) Meeting #78, Nov 04, 2025",
    "issueUrl": "https://github.com/ethereum/pm/issues/1791"
  },
  {
    "meeting": 77,
    "dateISO": "2025-10-28",
    "timeUTC": "16:00",
    "title": "EIP Editing Office Hour (EIP + ERC) Meeting #77, Oct 28, 2025",
    "issueUrl": "https://github.com/ethereum/pm/issues/1776"
  },
  {
    "meeting": 76,
    "dateISO": "2025-10-21",
    "timeUTC": "16:00",
    "title": "EIP Editing Office Hour (EIP Only) Meeting #76, Oct 21, 2025",
    "issueUrl": "https://github.com/ethereum/pm/issues/1775"
  },
  {
    "meeting": 75,
    "dateISO": "2025-10-14",
    "timeUTC": "16:00",
    "title": "EIP Editing Office Hour (EIP + ERC) Meeting #75, Oct 14, 2025",
    "issueUrl": "https://github.com/ethereum/pm/issues/1761"
  },
  {
    "meeting": 74,
    "dateISO": "2025-10-07",
    "timeUTC": "16:00",
    "title": "EIP Editing Office Hour (EIP + ERC) Meeting #74, Oct 07, 2025",
    "issueUrl": "https://github.com/ethereum/pm/issues/1752"
  },
  {
    "meeting": 73,
    "dateISO": "2025-09-23",
    "timeUTC": "16:00",
    "title": "EIP Editing Office Hour (EIP + ERC) Meeting #73, Sep 23, 2025",
    "issueUrl": "https://github.com/ethereum/pm/issues/1739"
  },
  {
    "meeting": 72,
    "dateISO": "2025-09-16",
    "timeUTC": "16:00",
    "title": "EIP Editing Office Hour (EIP) Meeting #72",
    "issueUrl": "https://github.com/ethereum/pm/issues/1726"
  },
  {
    "meeting": 71,
    "dateISO": "2025-09-09",
    "timeUTC": "16:00",
    "title": "EIP Editing Office Hour (EIP + ERC) Meeting #71, Sep 09, 2025",
    "issueUrl": "https://github.com/ethereum/pm/issues/1721"
  },
  {
    "meeting": 70,
    "dateISO": "2025-08-26",
    "timeUTC": "16:00",
    "title": "EIP Editing Office Hour (EIP + ERC) Meeting #70, Aug 26, 2025",
    "issueUrl": "https://github.com/ethereum/pm/issues/1702"
  },
  {
    "meeting": 69,
    "dateISO": "2025-08-19",
    "timeUTC": "16:00",
    "title": "EIP Editing Office Hour (EIP only) Meeting #69, Aug 19, 2025",
    "issueUrl": "https://github.com/ethereum/pm/issues/1693"
  },
  {
    "meeting": 68,
    "dateISO": "2025-08-05",
    "timeUTC": "16:00",
    "title": "EIP Editing Office Hour (EIP + ERC) Meeting #68, Aug 05, 2025",
    "issueUrl": "https://github.com/ethereum/pm/issues/1660"
  },
  {
    "meeting": 67,
    "dateISO": "2025-07-29",
    "timeUTC": null,
    "title": "EIP Editing Office Hour Meeting 67 (EIP+ERC), July 29, 2025",
    "issueUrl": "https://github.com/ethereum/pm/issues/1633"
  },
  {
    "meeting": 66,
    "dateISO": "2025-07-22",
    "timeUTC": null,
    "title": "EIP Editing Office Hour Meeting 66 (EIP) | July 22, 2025",
    "issueUrl": "https://github.com/ethereum/pm/issues/1623"
  },
  {
    "meeting": 65,
    "dateISO": "2025-07-15",
    "timeUTC": null,
    "title": "EIP Editing Office Hour Meeting 65 (EIP + ERC ) | July 15, 2025",
    "issueUrl": "https://github.com/ethereum/pm/issues/1620"
  },
  {
    "meeting": 64,
    "dateISO": "2025-07-08",
    "timeUTC": null,
    "title": "EIP Editing Office Hour Meeting 64 (EIP + ERC ) | July 08, 2025",
    "issueUrl": "https://github.com/ethereum/pm/issues/1596"
  },
  {
    "meeting": 63,
    "dateISO": "2025-06-24",
    "timeUTC": null,
    "title": "EIP Editing Office Hour Meeting 63 (EIP Only) | June 24, 2025",
    "issueUrl": "https://github.com/ethereum/pm/issues/1592"
  },
  {
    "meeting": 62,
    "dateISO": "2025-05-27",
    "timeUTC": null,
    "title": "EIP Editing Office Hour Meeting 62 (EIP + ERC) | May 27, 2025",
    "issueUrl": "https://github.com/ethereum/pm/issues/1557"
  },
  {
    "meeting": 61,
    "dateISO": "2025-05-20",
    "timeUTC": null,
    "title": "EIP Editing Office Hour Meeting 61 (EIP Only) | May 20, 2025",
    "issueUrl": "https://github.com/ethereum/pm/issues/1542"
  },
  {
    "meeting": 60,
    "dateISO": "2025-05-13",
    "timeUTC": null,
    "title": "EIP Editing Office Hour Meeting 60 (EIP+ERC) | May 13, 2025",
    "issueUrl": "https://github.com/ethereum/pm/issues/1540"
  },
  {
    "meeting": 59,
    "dateISO": "2025-04-29",
    "timeUTC": null,
    "title": "EIP Editing Office Hour Meeting 59 (EIP+ERC) | April 29, 2025",
    "issueUrl": "https://github.com/ethereum/pm/issues/1481"
  },
  {
    "meeting": 58,
    "dateISO": "2025-04-22",
    "timeUTC": null,
    "title": "EIP Editing Office Hour Meeting 58 (EIP) | April 22, 2025",
    "issueUrl": "https://github.com/ethereum/pm/issues/1476"
  },
  {
    "meeting": 57,
    "dateISO": "2025-04-15",
    "timeUTC": null,
    "title": "EIP Editing Office Hour Meeting 57 (EIP+ERC) | April 15, 2025",
    "issueUrl": "https://github.com/ethereum/pm/issues/1440"
  },
  {
    "meeting": 55,
    "dateISO": "2025-03-25",
    "timeUTC": null,
    "title": "EIP Editing Office Hour Meeting 55 (EIP Only) | March 25, 2025",
    "issueUrl": "https://github.com/ethereum/pm/issues/1403"
  }
];
